/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtistProfile {
  'bio' : string,
  'displayName' : string,
  'socialLinks' : [] | [
    {
      'twitter' : [] | [string],
      'instagram' : [] | [string],
      'website' : [] | [string],
    }
  ],
  'genres' : Array<string>,
}
export type ExternalBlob = Uint8Array;
export interface LyricDocument {
  'title' : string,
  'created' : Time,
  'content' : string,
  'tags' : Array<string>,
  'author' : Principal,
  'updated' : Time,
}
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface SongSnippet {
  'title' : string,
  'audio' : ExternalBlob,
  'published' : Time,
  'description' : string,
  'genres' : Array<string>,
  'uploader' : Principal,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'socialLinks' : [] | [
    {
      'twitter' : [] | [string],
      'instagram' : [] | [string],
      'website' : [] | [string],
    }
  ],
  'genres' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoiceNote {
  'title' : string,
  'created' : Time,
  'creator' : Principal,
  'audio' : ExternalBlob,
  'linkedLyric' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteLyric' : ActorMethod<[string], undefined>,
  'getArtistProfile' : ActorMethod<[Principal], [] | [ArtistProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getUserLyrics' : ActorMethod<[Principal], Array<LyricDocument>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSongSnippets' : ActorMethod<[Principal], Array<SongSnippet>>,
  'getUserVoiceNotes' : ActorMethod<[Principal], Array<VoiceNote>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishSongSnippet' : ActorMethod<
    [string, string, Array<string>, ExternalBlob],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLyric' : ActorMethod<[string, string, Array<string>], undefined>,
  'saveVoiceNote' : ActorMethod<
    [string, ExternalBlob, [] | [string]],
    undefined
  >,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'updateArtistProfile' : ActorMethod<[ArtistProfile], undefined>,
  'updateLyric' : ActorMethod<[string, string, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];