/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ArtistProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'socialLinks' : IDL.Opt(
    IDL.Record({
      'twitter' : IDL.Opt(IDL.Text),
      'instagram' : IDL.Opt(IDL.Text),
      'website' : IDL.Opt(IDL.Text),
    })
  ),
  'genres' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'socialLinks' : IDL.Opt(
    IDL.Record({
      'twitter' : IDL.Opt(IDL.Text),
      'instagram' : IDL.Opt(IDL.Text),
      'website' : IDL.Opt(IDL.Text),
    })
  ),
  'genres' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const LyricDocument = IDL.Record({
  'title' : IDL.Text,
  'created' : Time,
  'content' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Principal,
  'updated' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SongSnippet = IDL.Record({
  'title' : IDL.Text,
  'audio' : ExternalBlob,
  'published' : Time,
  'description' : IDL.Text,
  'genres' : IDL.Vec(IDL.Text),
  'uploader' : IDL.Principal,
});
export const VoiceNote = IDL.Record({
  'title' : IDL.Text,
  'created' : Time,
  'creator' : IDL.Principal,
  'audio' : ExternalBlob,
  'linkedLyric' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLyric' : IDL.Func([IDL.Text], [], []),
  'getArtistProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ArtistProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getUserLyrics' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LyricDocument)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSongSnippets' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SongSnippet)],
      ['query'],
    ),
  'getUserVoiceNotes' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VoiceNote)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishSongSnippet' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLyric' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'saveVoiceNote' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateArtistProfile' : IDL.Func([ArtistProfile], [], []),
  'updateLyric' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ArtistProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'socialLinks' : IDL.Opt(
      IDL.Record({
        'twitter' : IDL.Opt(IDL.Text),
        'instagram' : IDL.Opt(IDL.Text),
        'website' : IDL.Opt(IDL.Text),
      })
    ),
    'genres' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'socialLinks' : IDL.Opt(
      IDL.Record({
        'twitter' : IDL.Opt(IDL.Text),
        'instagram' : IDL.Opt(IDL.Text),
        'website' : IDL.Opt(IDL.Text),
      })
    ),
    'genres' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const LyricDocument = IDL.Record({
    'title' : IDL.Text,
    'created' : Time,
    'content' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Principal,
    'updated' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SongSnippet = IDL.Record({
    'title' : IDL.Text,
    'audio' : ExternalBlob,
    'published' : Time,
    'description' : IDL.Text,
    'genres' : IDL.Vec(IDL.Text),
    'uploader' : IDL.Principal,
  });
  const VoiceNote = IDL.Record({
    'title' : IDL.Text,
    'created' : Time,
    'creator' : IDL.Principal,
    'audio' : ExternalBlob,
    'linkedLyric' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLyric' : IDL.Func([IDL.Text], [], []),
    'getArtistProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ArtistProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserLyrics' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LyricDocument)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSongSnippets' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SongSnippet)],
        ['query'],
      ),
    'getUserVoiceNotes' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VoiceNote)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishSongSnippet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLyric' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'saveVoiceNote' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateArtistProfile' : IDL.Func([ArtistProfile], [], []),
    'updateLyric' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };