export const commonWords = [
  'love', 'above', 'dove', 'shove', 'glove',
  'heart', 'start', 'part', 'art', 'smart', 'chart',
  'night', 'light', 'right', 'sight', 'fight', 'bright', 'tight', 'flight', 'might',
  'day', 'way', 'say', 'play', 'stay', 'pay', 'may', 'bay', 'gray', 'ray',
  'time', 'rhyme', 'climb', 'prime', 'crime', 'lime', 'dime',
  'mind', 'find', 'kind', 'blind', 'behind', 'wind', 'grind',
  'dream', 'stream', 'team', 'beam', 'cream', 'scream', 'gleam',
  'soul', 'goal', 'whole', 'role', 'control', 'roll', 'toll', 'bowl',
  'fire', 'desire', 'wire', 'tire', 'higher', 'inspire', 'acquire',
  'pain', 'rain', 'gain', 'main', 'train', 'brain', 'chain', 'plain', 'strain',
  'free', 'see', 'be', 'tree', 'key', 'me', 'we', 'three', 'agree', 'degree',
  'life', 'wife', 'knife', 'strife', 'rife',
  'world', 'swirled', 'hurled', 'unfurled', 'curled',
  'feel', 'real', 'deal', 'heal', 'steal', 'reveal', 'appeal', 'seal',
  'know', 'show', 'flow', 'grow', 'slow', 'glow', 'throw', 'blow', 'low',
  'high', 'sky', 'fly', 'try', 'cry', 'dry', 'why', 'buy', 'die', 'lie',
  'strong', 'long', 'song', 'wrong', 'belong', 'along',
  'true', 'blue', 'new', 'few', 'view', 'through', 'knew', 'grew', 'flew',
  'face', 'place', 'space', 'race', 'grace', 'trace', 'case', 'base',
  'eyes', 'skies', 'lies', 'tries', 'cries', 'flies', 'rise', 'wise', 'size',
  'home', 'dome', 'roam', 'chrome', 'foam', 'comb',
  'alone', 'phone', 'stone', 'bone', 'tone', 'zone', 'throne', 'known', 'grown',
  'away', 'today', 'okay', 'decay', 'display', 'betray', 'delay',
  'back', 'track', 'black', 'pack', 'crack', 'stack', 'attack', 'lack',
  'ground', 'sound', 'found', 'round', 'bound', 'pound', 'around', 'profound',
  'side', 'ride', 'hide', 'pride', 'wide', 'guide', 'slide', 'tide', 'inside',
  'hand', 'stand', 'land', 'band', 'sand', 'grand', 'brand', 'understand',
  'head', 'dead', 'red', 'bed', 'said', 'spread', 'thread', 'instead',
  'cold', 'gold', 'hold', 'old', 'bold', 'told', 'sold', 'fold',
  'young', 'sung', 'hung', 'lung', 'rung', 'swung', 'tongue',
  'fear', 'near', 'clear', 'hear', 'tear', 'year', 'dear', 'appear', 'sincere',
  'move', 'prove', 'groove', 'improve', 'remove',
  'change', 'range', 'strange', 'arrange', 'exchange',
  'end', 'friend', 'send', 'spend', 'blend', 'trend', 'defend', 'pretend',
  'call', 'fall', 'all', 'ball', 'wall', 'hall', 'small', 'tall', 'install',
  'run', 'sun', 'fun', 'gun', 'done', 'one', 'won', 'begun',
  'game', 'name', 'same', 'fame', 'blame', 'frame', 'claim', 'shame',
  'best', 'rest', 'test', 'west', 'chest', 'guest', 'quest', 'blessed',
  'lost', 'cost', 'frost', 'crossed', 'tossed',
  'break', 'take', 'make', 'wake', 'shake', 'fake', 'sake', 'mistake',
  'turn', 'burn', 'learn', 'return', 'concern', 'earn',
  'keep', 'deep', 'sleep', 'sweep', 'weep', 'steep', 'leap',
  'fast', 'last', 'past', 'cast', 'vast', 'blast', 'contrast',
  'shine', 'mine', 'line', 'fine', 'sign', 'wine', 'divine', 'design', 'combine',
  'hope', 'cope', 'rope', 'scope', 'slope',
  'wait', 'fate', 'late', 'gate', 'hate', 'state', 'create', 'relate',
  'walk', 'talk', 'chalk', 'stalk',
  'rise', 'prize', 'wise', 'size', 'disguise', 'realize', 'surprise',
  'fight', 'night', 'sight', 'right', 'light', 'might', 'tight', 'flight',
];
